### ISSUE TITLE
Uh oh "Looks like something went wrong" -Yahoo

### ISSUE THREAD

**Issue by malf922** [landonp1203/yahoo-fantasy-bot#11] opened 2019-06-21 20:01 UTC
Getting the above message when trying to open app from Hiroku to complete the setup process. I think it may be due to Yahoo not allowing 'HEROKU-APP-NAME'.herokuapp.com as the redirect URI due to it being an invalid URL. I had to add https:// to the front in order for Yahoo Developer to accept it.

**Comment by landonp1203** [comment] 2019-07-11 03:30
I will look into this, but the bot worked properly afterwards?

**Comment by DMcP89** [comment] 2019-07-18 02:36
Running into the same issue

**Comment by DMcP89** [comment] 2019-07-18 06:52
@malf922 figured this out. On your Yahoo app configuration, add /auth to the end of the uri. For example:

https://HEROKU-APP-NAME'.herokuapp.com/auth

The issue is caused by the authenticationUrl method of the Server class. It adds on /auth to the end of the URL. 

@landonp1203 the readme should be updated accordingly.

**Comment by malf922** [comment] 2019-07-18 12:41
@DMcP89 Yes! That appears to have done the trick. Thank you!

**Comment by landonp1203** [comment] 2019-07-18 18:45
I am going to be updating this application with a ReactiveX implementation sometime in the next month, so be on the look out for that, I will then update accordingly on what do.  As of now, I don't have the time to work on this because of my new job, but I will start looking this weekend at new implementations as I know there are better, more concise ways to do this.

**Comment by DMcP89** [comment] 2019-07-19 14:12
@landonp1203 congrats on the new job. Opened a PR with the change to the read me.

**Comment by gregthedreg** [comment] 2019-08-02 13:35
thanks this helped!, were you able to open the app afterwards? thats where i got stuck next.

**Comment by gregthedreg** [comment] 2019-08-02 13:53
i made sure the url matched the one in this thread with the /auth at the end. im not too sure what i need to do to make this work.

**Comment by gregthedreg** [comment] 2019-08-02 16:15
2019-08-02T15:15:00.295016+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-8] 2019-08-02 15:15:00,294 [utils.JobRunner] - Server kept alive...
2019-08-02T15:20:00.001338+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-9] 2019-08-02 15:20:00,001 [utils.JobRunner] - Keeping server alive...
2019-08-02T15:20:00.993357+00:00 heroku[router]: at=info method=GET path="/keepalive" host=vipfantasy.herokuapp.com request_id=fae026c8-0081-4cbe-9d22-248830f0c834 fwd="18.234.239.46" dyno=web.1 connect=0ms service=3ms status=200 bytes=149 protocol=https
2019-08-02T15:20:00.996095+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-9] 2019-08-02 15:20:00,995 [utils.JobRunner] - Server kept alive...
2019-08-02T15:25:00.041064+00:00 heroku[router]: at=info method=GET path="/keepalive" host=vipfantasy.herokuapp.com request_id=4a55c3a5-1c40-4bfa-a31a-b77c7fb478b8 fwd="18.234.239.46" dyno=web.1 connect=1ms service=3ms status=200 bytes=149 protocol=https
2019-08-02T15:25:00.002088+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-10] 2019-08-02 15:25:00,001 [utils.JobRunner] - Keeping server alive...
2019-08-02T15:25:00.046012+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-10] 2019-08-02 15:25:00,045 [utils.JobRunner] - Server kept alive...
2019-08-02T15:30:00.002064+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-1] 2019-08-02 15:30:00,001 [utils.JobRunner] - Keeping server alive...
2019-08-02T15:30:00.339803+00:00 heroku[router]: at=info method=GET path="/keepalive" host=vipfantasy.herokuapp.com request_id=a3896c87-c6a7-4b8f-8f04-48390728c622 fwd="18.234.239.46" dyno=web.1 connect=0ms service=3ms status=200 bytes=149 protocol=https
2019-08-02T15:30:00.342447+00:00 app[web.1]: [DEBUG] [DefaultQuartzScheduler_Worker-1] 2019-08-02 15:30:00,342 [utils.JobRunner] - Server kept alive...
2019-08-02T15:32:40.940685+00:00 heroku[router]: at=info method=GET path="/" host=vipfantasy.herokuapp.com request_id=31f87ec5-fffd-4dfb-b5b7-5e8b9559dfa1 fwd="63.234.182.212" dyno=web.1 connect=0ms service=11ms status=302 bytes=353 protocol=https

does this look like i fixed it? i still cant test it because i am at work and for some reason they blocked me from going further.

**Comment by gregthedreg** [comment] 2019-08-03 02:10
i finally got it after some magic. now is there a way to test this or command cheat sheet that i am missing? or will this be set till our league sees action? i kinda want to test this before i start inviting my friends to the discord.

**Comment by landonp1203** [comment] 2019-08-03 14:21
I am going to be rewriting the entire bot this weekend @gregthedreg, so hold off until I push the new version :)

**Comment by gregthedreg** [comment] 2019-08-03 14:29
Well I finally got it through last night. Im looking forward to the rewrite. My league is super excited for your bot lol.

**Comment by landonp1203** [comment] 2019-08-07 00:10
The changes are taking longer than I expected, since I am learning Rx at the same time.  It will be done in the next 2 weeks, and the latest by the first week of the season. @gregthedreg

**Comment by gregthedreg** [comment] 2019-08-07 00:14
Would the current bot work till then?

**Comment by landonp1203** [comment] 2019-08-10 02:44
Yes it should

**Comment by lud024** [comment] 2019-08-18 23:44
Any update on this? I just got everything setup, when I open app I get the same error from yahoo.

**Comment by red-scott** [comment] 2019-09-02 23:21
As @malf922 mentioned, needed to prepend https:// to the heroku app URL, and can confirm it works. Picked up a kicker for the season to confirm.

![image](https://user-images.githubusercontent.com/25727552/64135468-8909aa80-cd84-11e9-94b2-84a735bf7af5.png)

**Comment by kabirsikand** [comment] 2019-09-03 22:42
@landonp1203 updates? Can help if needed....week 1 around the corner!

**Comment by landonp1203** [comment] 2019-09-04 05:05
@kabirsikand it will be done by either Wednesday night or early Thursday morning...if you look at the rn branch, you’ll see what I’ve been working on.  Thanks for the help! Contribute however you’d like :)

**Comment by landonp1203** [comment] 2019-09-05 14:39
Just finishing up, making sure bot works with Yahoo now, and will make post within the next hour-2!

**Comment by Jonath22b** [comment] 2019-09-05 16:10
Hey @landonp1203 the bot is working but on Heroku the dyno's now show "Web" & "Bot" the authorization is working but the bot won't work on discord without having the "Bot" dyno turned on.  Problem is it keeps sending out notifications about league updates that happened weeks ago in a constant cycle. There seems to be no setting for the bot to only push new Alerts rather than all Alerts. Any ideas on how to fix this? 
![Screen Shot 2019-09-05 at 12 09 49 PM](https://user-images.githubusercontent.com/53913509/64359328-1a239000-cfd6-11e9-960c-79b364011dc1.png)

**Comment by landonp1203** [comment] 2019-09-05 16:32
All done https://www.reddit.com/r/fantasyfootball/comments/d032cw/discord_groupme_and_slack_yahoo_fantasy_football/

**Comment by landonp1203** [comment] 2019-09-05 16:32
@Jonath22b I fixed that issue, delete the app and redeploy it.  That should fix it.  If not, please post in this issue so I can look at it.

Thanks!

**Comment by malf922** [comment] 2019-09-05 16:51
@landonp1203 on the https://developer.yahoo.com/apps/ portion of the guide, step 3c still seems inaccurate. I had to add https:// in order to get it to authorize. I could see that generating a lot of questions on the Reddit post.

**Comment by landonp1203** [comment] 2019-09-05 17:22
I actually did at that to the README when I realized it, you probably saw it right before I changed it.

**Comment by landonp1203** [comment] 2019-09-05 21:49
Timing and alert changes.  Please update so no null pointer exceptions and missing alerts. @malf922 @DMcP89 @gregthedreg @ackleymi

**Comment by Jonath22b** [comment] 2019-09-05 21:51
@landonp1203 just did the update - still working well! Thank you

**Comment by landonp1203** [comment] 2019-09-05 22:02
Sorry last update just pushed, fixed the build and removed an erroneous field in the matchups message.  If it’s working for you now, you should be fine and you’ll just have the extra field. @Jonath22b

**Comment by landonp1203** [comment] 2019-09-06 02:51
Closing as this pertains to an old version of the bot that is non-existent anymore.

**Closed by landonp1203** 2019-09-06 02:51 UTC
Labels: general discussion
